---
name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          sudo apt install latexmk texlive-latex-base texlive-latex-extra texlive-latex-recommended

      - name: "Build"
        run: |
          latexmk -pdf main.tex
          mv "main.pdf" "UFSIT Constitution.pdf"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            *.pdf
